name: sentimentr-deployment

director_uuid: PLACEHOLDER-DIRECTOR-UUID

releases:
- {name: sentimentr-release, version: latest}

resource_pools:
- name: small
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
      name: random

networks:
- name: default
  type: dynamic
  cloud_properties:
    name: random


###########
- name: s1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.5.0/30
    reserved:
    - 10.244.5.1
    static:
    - 10.244.5.2
#  - cloud_properties:
#    name: random
#     range: 10.244.0.4/30
#     reserved:
#     - 10.244.0.5
#     static:
#     - 10.244.0.6

###########

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
- name: sentimentr
  instances: 1
  templates:
  - {name: sentimentr, release: sentimentr-release}
  resource_pool: small
  networks:
  - name: s1
    static_ips:
    - 10.244.5.2

  #############

- name: sentimentr-service-broker
  instances: 1
  templates:
  - {name: sentimentr-service-broker, release: sentimentr-release}
  resource_pool: small
  networks:
  - name: default
  run-after:
  - sentimentr

properties:
  sentimentr-service-broker:
    sentimentr:
      host: (( jobs.sentimentr.networks.s1.static_ips.[0] ))
